### ISSUE TITLE
List display improvement

### ISSUE THREAD

**Issue by stevemats** [INIT6Source/Hacker_Discords#11]
Suggesting to add/improve the following:
Adding a Table of Contents (ToC) for the Discord
Organize the list of Discord servers in a more structured order (0-9, A-Z)

**Comment by INIT6Source** [comment]
I don't have the time to do it personally but if you wanted to make the same UX changes to [Hacker-Hiring](https://github.com/INIT6Source/Hacker_Hiring_Discords) @stevemats
